In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 1.01324349,  1.21312005,  0.89500509, ..., -0.05149655,
        -0.65648554, -0.25042427],
       [-0.55662429,  2.50635718, -0.62656464, ..., -1.77517473,
        -0.81116765, -0.93258574],
       [ 0.00364655, -0.5912873 , -0.10782938, ..., -1.26945119,
        -0.73138424, -1.28527171],
       ...,
       [-0.50392554,  0.13188901, -0.50533846, ..., -0.61821645,
        -0.36177542, -0.35458835],
       [ 0.40859477, -0.02593774,  0.56878183, ...,  1.46430846,
         2.17826762,  1.19428616],
       [-0.72026775, -0.74440281, -0.70429438, ..., -0.28592285,
        -0.16801572, -0.20739998]])

In [9]:
y_train

274    M
473    B
270    B
456    B
446    M
      ..
131    M
326    B
301    B
351    M
488    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [23]:
#Define the model
class mysimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights)+self.bias
    y_pred =  torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [28]:
learning_rate = 0.1
epochs = 25

In [30]:
#Training pipeline
model = mysimpleNN(X_train_tensor)
model.weights

#define loop
for epoch in range(epochs):
#forward pass
  y_pred = model.forward(X_train_tensor)


#loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  #print(loss)

#backward pass
  loss.backward()


#parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.9566775082576964
Epoch: 2, Loss: 2.798724735939635
Epoch: 3, Loss: 2.636394078847555
Epoch: 4, Loss: 2.470752455479632
Epoch: 5, Loss: 2.306117679641345
Epoch: 6, Loss: 2.141340171367935
Epoch: 7, Loss: 1.9826084610559376
Epoch: 8, Loss: 1.8292273879247836
Epoch: 9, Loss: 1.677260709739957
Epoch: 10, Loss: 1.5318001872246083
Epoch: 11, Loss: 1.3936594990247662
Epoch: 12, Loss: 1.267758110935203
Epoch: 13, Loss: 1.1582183924454366
Epoch: 14, Loss: 1.066084709539658
Epoch: 15, Loss: 0.9914268767022908
Epoch: 16, Loss: 0.933099772867066
Epoch: 17, Loss: 0.8888623880969778
Epoch: 18, Loss: 0.8558631015092901
Epoch: 19, Loss: 0.8312464768459017
Epoch: 20, Loss: 0.8125861196229532
Epoch: 21, Loss: 0.7980399665031126
Epoch: 22, Loss: 0.7863106073503354
Epoch: 23, Loss: 0.7765279360334137
Epoch: 24, Loss: 0.7681260895546953
Epoch: 25, Loss: 0.7607429011527946


In [31]:
model.bias

tensor([-0.1485], dtype=torch.float64, requires_grad=True)

In [32]:
model.weights

tensor([[-0.2626],
        [ 0.1566],
        [ 0.0874],
        [-0.0935],
        [ 0.0370],
        [-0.4539],
        [ 0.1732],
        [ 0.1226],
        [-0.2536],
        [ 0.3475],
        [ 0.0422],
        [ 0.4245],
        [ 0.1884],
        [ 0.0658],
        [-0.0670],
        [ 0.1694],
        [ 0.4486],
        [-0.2183],
        [ 0.1696],
        [-0.2725],
        [ 0.3346],
        [ 0.0804],
        [ 0.1025],
        [-0.2742],
        [ 0.4020],
        [-0.1817],
        [-0.4293],
        [ 0.1981],
        [-0.0425],
        [-0.1581]], dtype=torch.float64, requires_grad=True)

In [36]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')
  print(y_pred)

Accuracy: 0.6946752667427063
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
     